version: "3.9"
services:
  app-cicd:
    build: .
    container_name: app-poli
    ports:
      - "8080:8080"
    links:
      - mysqldb
    env_file:
      - .env
      
  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=a$MYSQL_DATABASE

  jenkins-poli:
    image: jenkins/jenkins
    container_name: jenkins-poli
    ports:
      - "8000:8080"
    